version: '2.4'
volumes:
  db_data:
services:
  db:
    image: percona:5.6.37
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: foo
    mem_limit: 2g
